### ISSUE TITLE
1.6: New Typedef field: value_type

### ISSUE THREAD

**Issue by cmungall** [owlcollab/oboformat#135]
submitter: @balhoff 

- Similar to JSON-LD @type
- Might save us from using syntax to distinguish IRIs from strings

example:

```yaml
[Typedef]
id: term_tracker_item
name: term tracker item
namespace: external
xref: IAO:0000233
is_metadata_tag: true
is_class_level: true
value_type: IRI
```

@cmungall:

I think we can just use range to do this
