### ISSUE TITLE
Annotation assertions should not show up as relationship tags

### ISSUE THREAD

**Issue by cmungall** [owlcollab/oboformat#144]
Uberon now looks like this:

```yaml
id: UBERON:8600017
name: bronchopulmonary segment
def: "A discrete anatomical unit of the lung that is composed of a segmental bronchus and the lung tissue supplied by that bronchus. A bronchopulmonary segment exhibits a pyramidal shape, with its apex pointing towards the center of the lung and its base toward the pleural surface." [doi:10.1016/j.mpaic.2008.09.022, FMA:7312, PMID:18271171, PMID:33620799]
comment: A bronchopulmonary segment is surrounded by connective tissue septa, which are continuous with the pleural surface and prevent air collateralization between segments somewhat. In humans, the right lung has ten bronchopulmonary segments and eight or nine bronchopulmonary segments in the left lung. {xref="doi:10.1016/j.mpaic.2008.09.022", xref="PMID:18271171"}
synonym: "lung segment" EXACT [PMID:33620799]
is_a: UBERON:0000063 ! organ subunit
relationship: contributes_to_morphology_of UBERON:0000101 ! lobe of lung
relationship: dc-contributor https://orcid.org/0000-0001-6677-8489
relationship: dc-contributor https://orcid.org/0000-0002-9185-3994
relationship: part_of UBERON:0000101 ! lobe of lung
property_value: dcterms-date "2023-07-20T12:43:29Z" xsd:dateTime
```

this is horrible aesthetically and also massively confusing to consumers of the obo file.

the current spec is allows an annotation assertion to a node to be serialized as *either* a `relationship` or a `property_value`. There is a separate tag on the Typedef that prevents relationship being interpreted as existential.

Previously the default owl serialization was to us PV, but something has changed

in 1.6, either

1. mandate using PV
2. allow either, but make PV the default for serialization
