### ISSUE TITLE
oboformat loader should generated subAnnotationPropertyOf when is_a is used between Typedefs with is_metadata_tag

### ISSUE THREAD

**Issue by cmungall** [owlcollab/oboformat#147]
```yaml
[Typedef]
id: R:1
is_a: R:2
is_metadata_tag: true
```

This should generated a subPropertyOf
