### ISSUE TITLE
Roundtrip to annotation properties does not work

### ISSUE THREAD

**Issue by cmungall** [owlcollab/oboformat#152]
This converts to OWL as expected

```yaml
[Typedef]
id: OMO:1
name: test
is_metadata_tag: true
```

the `is_metadata_tag` is retained as an annotation, which is not strictly necessary. If this annotation is removed, then the AP is dropped when converting back to OWL.

https://github.com/information-artifact-ontology/ontology-metadata/issues/181
